[package]
authors = ["Juliette Cordor"]
categories = ["development-tools", "os", "os::unix-apis", "os::windows-apis"]
description = "A collection of small things that don't deserve their own crate"
documentation = "https://docs.rs/quork"
edition = "2021"
homepage = "https://github.com/jewlexx/quork.git"
keywords = ["admin", "linux", "network", "sys", "windows"]
license = "MIT OR Apache-2.0"
name = "quork"
repository = "https://github.com/jewlexx/quork.git"
rust-version = "1.70.0"
version = "0.8.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["quork-proc"]

[dependencies]
cfg-if = "1.0"
lock_api = { version = "0.4", optional = true }
parking_lot = { version = "0.12", optional = true }
quork-proc = { version = "0.4", path = "quork-proc", optional = true }
spin = { version = "0.10", optional = true }
thiserror = { version = "2.0" }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
    "Win32_System_Com",
    "Win32_Networking_NetworkListManager",
], optional = true }
windows-sys = { version = "0.59.0", features = [
    "Win32_Foundation",
    "Win32_Networking",
    "Win32_Security",
    "Win32_Security",
    "Win32_System_Com",
    "Win32_System_Threading",
] }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29", features = ["user"] }

[features]
all = ["macros", "network", "root", "std", "traits", "sized_string"]
default = ["all"]
macros = ["quork-proc"]
network = ["windows"]
root = ["std"]
sized_string = []
std = []
traits = []

[dev-dependencies]
is-root = "0.1"
